.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH remote-luks-unlocker 1  "remote-luks-unlocker " 
.SH NAME
remote\-luks\-unlocker \- Poll an SSH endpoint and run a LUKS unlock command
.SH SYNOPSIS
\fBremote\-luks\-unlocker\fR [\fB\-p \fR] [\fB\-i \fR] [\fB\-4 \fR] [\fB\-6 \fR] [\fB\-B \fR] [\fB\-b \fR] [\fB\-C \fR] [\fB\-c \fR] [\fB\-F \fR] [\fB\-I \fR] [\fB\-J \fR] [\fB\-m \fR] [\fB\-P \fR] [\fB\-\-known\-hosts\fR] [\fB\-\-failure\-interval\fR] [\fB\-\-success\-interval\fR] [\fB\-\-once\fR] [\fB\-\-max\-runtime\fR] [\fB\-\-attempt\-timeout\fR] [\fB\-\-connect\-timeout\fR] [\fB\-\-command\fR] [\fB\-v \fR]... [\fB\-h\fR|\fB\-\-help\fR] <\fB\-\-luks\-password\fR> <\fIDESTINATION\fR> 
.SH DESCRIPTION
Poll an SSH endpoint and run a LUKS unlock command
.SH OPTIONS
.TP
\fB\-p\fR \fI<PORT>\fR [default: 22]
SSH port
.TP
\fB\-\-luks\-password\fR \fI<LUKS_PASSWORD>\fR
Passphrase sent to the remote unlock command
.TP
\fB\-i\fR \fI<IDENTITY_FILE>\fR
Private SSH identity file whose public key is authorized on the server
.TP
\fB\-4\fR
Force IPv4 address resolution
.TP
\fB\-6\fR
Force IPv6 address resolution
.TP
\fB\-B\fR \fI<bind_interface>\fR
Bind to a network interface before connecting
.TP
\fB\-b\fR \fI<bind_address>\fR
Bind to a local source address before connecting
.TP
\fB\-C\fR
Request compression
.TP
\fB\-c\fR \fI<cipher_spec>\fR
Select the cipher specification
.TP
\fB\-F\fR \fI<configfile>\fR
Select an alternative SSH configuration file
.TP
\fB\-I\fR \fI<pkcs11>\fR
Select a PKCS#11 provider
.TP
\fB\-J\fR \fI<destination>\fR
Connect through a jump host
.TP
\fB\-m\fR \fI<mac_spec>\fR
Select the MAC algorithms
.TP
\fB\-P\fR \fI<tag>\fR
Select an SSH configuration tag
.TP
\fB\-\-known\-hosts\fR \fI<KNOWN_HOSTS>\fR
Optional `known_hosts` file used to verify the remote host key. When omitted, OpenSSH uses its normal known\-hosts files
.TP
\fB\-\-failure\-interval\fR \fI<FAILURE_INTERVAL>\fR [default: 15s]
Delay after a failed SSH attempt before retrying, such as `1s` or `1m`
.TP
\fB\-\-success\-interval\fR \fI<SUCCESS_INTERVAL>\fR [default: 1m]
Delay between successful remote command runs in continuous mode
.TP
\fB\-\-once\fR
Retry until the first successful unlock, then exit
.TP
\fB\-\-max\-runtime\fR \fI<MAX_RUNTIME>\fR
Maximum total runtime before exiting with an error, such as `10m`
.TP
\fB\-\-attempt\-timeout\fR \fI<ATTEMPT_TIMEOUT>\fR [default: 30s]
Maximum time allowed for one SSH connection and command attempt, such as `30s` or `1m`
.TP
\fB\-\-connect\-timeout\fR \fI<CONNECT_TIMEOUT>\fR [default: 2s]
Maximum time OpenSSH may spend establishing one connection, such as `2s` or `10s`
.TP
\fB\-\-command\fR \fI<COMMAND>\fR [default: cryptroot\-unlock]
Remote command to run after authentication
.TP
\fB\-v\fR
Increase OpenSSH diagnostics; repeat for more detail (`\-v`, `\-vv`, or `\-vvv`)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIDESTINATION\fR>
SSH destination in `[user@]host` form
